allowLineBreaksInTitles: false
color: pink
description: null
fieldLayouts:
  6a52c853-257a-490a-b032-be3c5f33a9e7:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        name: Content
        uid: 8fa1c20f-9485-449d-8fd6-a1ca7c45386b
        userCondition: null
    thumbFieldKey: null
handle: blockBlog
hasTitleField: false
icon: blogger
name: Blog
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
